import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import org.junit.Test;
import types.testing.AbstractTestSuite;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class TestSuite_3_1c extends AbstractTestSuite {
	public static class Part_0 {
		@Test public void test_0() { testValid("any","any"); }
		@Test public void test_1() { testValid("any","int"); }
		@Test public void test_2() { testValid("any","{any}"); }
		@Test public void test_3() { testValid("any","{int}"); }
		@Test public void test_4() { testValid("any","!any"); }
		@Test public void test_5() { testValid("any","!int"); }
		@Test public void test_6() { testValid("any","{{any}}"); }
		@Test public void test_7() { testValid("any","{{int}}"); }
		@Test public void test_8() { testValid("any","{!int}"); }
		@Test public void test_9() { testValid("any","!{any}"); }
		@Test public void test_10() { testValid("any","!{int}"); }
		@Test public void test_11() { testValid("any","!!any"); }
		@Test public void test_12() { testValid("any","!!int"); }
		@Test public void test_13() { testValid("any","{{{any}}}"); }
		@Test public void test_14() { testValid("any","{{{int}}}"); }
		@Test public void test_15() { testValid("any","{{!int}}"); }
		@Test public void test_16() { testValid("any","{!{any}}"); }
		@Test public void test_17() { testValid("any","{!{int}}"); }
		@Test public void test_18() { testValid("any","{!!any}"); }
		@Test public void test_19() { testValid("any","{!!int}"); }
		@Test public void test_20() { testValid("any","!{{any}}"); }
		@Test public void test_21() { testValid("any","!{{int}}"); }
		@Test public void test_22() { testValid("any","!{!int}"); }
		@Test public void test_23() { testValid("any","!!{any}"); }
		@Test public void test_24() { testValid("any","!!{int}"); }
		@Test public void test_25() { testValid("any","!!!any"); }
		@Test public void test_26() { testValid("any","!!!int"); }
		@Test public void test_27() { testInvalid("int","any"); }
		@Test public void test_28() { testValid("int","int"); }
		@Test public void test_29() { testInvalid("int","{any}"); }
		@Test public void test_30() { testInvalid("int","{int}"); }
		@Test public void test_31() { testValid("int","!any"); }
		@Test public void test_32() { testInvalid("int","!int"); }
		@Test public void test_33() { testInvalid("int","{{any}}"); }
		@Test public void test_34() { testInvalid("int","{{int}}"); }
		@Test public void test_35() { testInvalid("int","{!int}"); }
		@Test public void test_36() { testInvalid("int","!{any}"); }
		@Test public void test_37() { testInvalid("int","!{int}"); }
		@Test public void test_38() { testInvalid("int","!!any"); }
		@Test public void test_39() { testValid("int","!!int"); }
		@Test public void test_40() { testInvalid("int","{{{any}}}"); }
		@Test public void test_41() { testInvalid("int","{{{int}}}"); }
		@Test public void test_42() { testInvalid("int","{{!int}}"); }
		@Test public void test_43() { testInvalid("int","{!{any}}"); }
		@Test public void test_44() { testInvalid("int","{!{int}}"); }
		@Test public void test_45() { testInvalid("int","{!!any}"); }
		@Test public void test_46() { testInvalid("int","{!!int}"); }
		@Test public void test_47() { testInvalid("int","!{{any}}"); }
		@Test public void test_48() { testInvalid("int","!{{int}}"); }
		@Test public void test_49() { testInvalid("int","!{!int}"); }
		@Test public void test_50() { testInvalid("int","!!{any}"); }
		@Test public void test_51() { testInvalid("int","!!{int}"); }
		@Test public void test_52() { testValid("int","!!!any"); }
		@Test public void test_53() { testInvalid("int","!!!int"); }
		@Test public void test_54() { testInvalid("{any}","any"); }
		@Test public void test_55() { testInvalid("{any}","int"); }
		@Test public void test_56() { testValid("{any}","{any}"); }
		@Test public void test_57() { testValid("{any}","{int}"); }
		@Test public void test_58() { testValid("{any}","!any"); }
		@Test public void test_59() { testInvalid("{any}","!int"); }
		@Test public void test_60() { testValid("{any}","{{any}}"); }
		@Test public void test_61() { testValid("{any}","{{int}}"); }
		@Test public void test_62() { testValid("{any}","{!int}"); }
		@Test public void test_63() { testInvalid("{any}","!{any}"); }
		@Test public void test_64() { testInvalid("{any}","!{int}"); }
		@Test public void test_65() { testInvalid("{any}","!!any"); }
		@Test public void test_66() { testInvalid("{any}","!!int"); }
		@Test public void test_67() { testValid("{any}","{{{any}}}"); }
		@Test public void test_68() { testValid("{any}","{{{int}}}"); }
		@Test public void test_69() { testValid("{any}","{{!int}}"); }
		@Test public void test_70() { testValid("{any}","{!{any}}"); }
		@Test public void test_71() { testValid("{any}","{!{int}}"); }
		@Test public void test_72() { testValid("{any}","{!!any}"); }
		@Test public void test_73() { testValid("{any}","{!!int}"); }
		@Test public void test_74() { testInvalid("{any}","!{{any}}"); }
		@Test public void test_75() { testInvalid("{any}","!{{int}}"); }
		@Test public void test_76() { testInvalid("{any}","!{!int}"); }
		@Test public void test_77() { testValid("{any}","!!{any}"); }
		@Test public void test_78() { testValid("{any}","!!{int}"); }
		@Test public void test_79() { testValid("{any}","!!!any"); }
		@Test public void test_80() { testInvalid("{any}","!!!int"); }
		@Test public void test_81() { testInvalid("{int}","any"); }
		@Test public void test_82() { testInvalid("{int}","int"); }
		@Test public void test_83() { testInvalid("{int}","{any}"); }
		@Test public void test_84() { testValid("{int}","{int}"); }
		@Test public void test_85() { testValid("{int}","!any"); }
		@Test public void test_86() { testInvalid("{int}","!int"); }
		@Test public void test_87() { testInvalid("{int}","{{any}}"); }
		@Test public void test_88() { testInvalid("{int}","{{int}}"); }
		@Test public void test_89() { testInvalid("{int}","{!int}"); }
		@Test public void test_90() { testInvalid("{int}","!{any}"); }
		@Test public void test_91() { testInvalid("{int}","!{int}"); }
		@Test public void test_92() { testInvalid("{int}","!!any"); }
		@Test public void test_93() { testInvalid("{int}","!!int"); }
		@Test public void test_94() { testInvalid("{int}","{{{any}}}"); }
		@Test public void test_95() { testInvalid("{int}","{{{int}}}"); }
		@Test public void test_96() { testInvalid("{int}","{{!int}}"); }
		@Test public void test_97() { testInvalid("{int}","{!{any}}"); }
		@Test public void test_98() { testInvalid("{int}","{!{int}}"); }
		@Test public void test_99() { testInvalid("{int}","{!!any}"); }
		@Test public void test_100() { testValid("{int}","{!!int}"); }
		@Test public void test_101() { testInvalid("{int}","!{{any}}"); }
		@Test public void test_102() { testInvalid("{int}","!{{int}}"); }
		@Test public void test_103() { testInvalid("{int}","!{!int}"); }
		@Test public void test_104() { testInvalid("{int}","!!{any}"); }
		@Test public void test_105() { testValid("{int}","!!{int}"); }
		@Test public void test_106() { testValid("{int}","!!!any"); }
		@Test public void test_107() { testInvalid("{int}","!!!int"); }
		@Test public void test_108() { testInvalid("!any","any"); }
		@Test public void test_109() { testInvalid("!any","int"); }
		@Test public void test_110() { testInvalid("!any","{any}"); }
		@Test public void test_111() { testInvalid("!any","{int}"); }
		@Test public void test_112() { testValid("!any","!any"); }
		@Test public void test_113() { testInvalid("!any","!int"); }
		@Test public void test_114() { testInvalid("!any","{{any}}"); }
		@Test public void test_115() { testInvalid("!any","{{int}}"); }
		@Test public void test_116() { testInvalid("!any","{!int}"); }
		@Test public void test_117() { testInvalid("!any","!{any}"); }
		@Test public void test_118() { testInvalid("!any","!{int}"); }
		@Test public void test_119() { testInvalid("!any","!!any"); }
		@Test public void test_120() { testInvalid("!any","!!int"); }
		@Test public void test_121() { testInvalid("!any","{{{any}}}"); }
		@Test public void test_122() { testInvalid("!any","{{{int}}}"); }
		@Test public void test_123() { testInvalid("!any","{{!int}}"); }
		@Test public void test_124() { testInvalid("!any","{!{any}}"); }
		@Test public void test_125() { testInvalid("!any","{!{int}}"); }
		@Test public void test_126() { testInvalid("!any","{!!any}"); }
		@Test public void test_127() { testInvalid("!any","{!!int}"); }
		@Test public void test_128() { testInvalid("!any","!{{any}}"); }
		@Test public void test_129() { testInvalid("!any","!{{int}}"); }
		@Test public void test_130() { testInvalid("!any","!{!int}"); }
		@Test public void test_131() { testInvalid("!any","!!{any}"); }
		@Test public void test_132() { testInvalid("!any","!!{int}"); }
		@Test public void test_133() { testValid("!any","!!!any"); }
		@Test public void test_134() { testInvalid("!any","!!!int"); }
		@Test public void test_135() { testInvalid("!int","any"); }
		@Test public void test_136() { testInvalid("!int","int"); }
		@Test public void test_137() { testValid("!int","{any}"); }
		@Test public void test_138() { testValid("!int","{int}"); }
		@Test public void test_139() { testValid("!int","!any"); }
		@Test public void test_140() { testValid("!int","!int"); }
		@Test public void test_141() { testValid("!int","{{any}}"); }
		@Test public void test_142() { testValid("!int","{{int}}"); }
		@Test public void test_143() { testValid("!int","{!int}"); }
		@Test public void test_144() { testInvalid("!int","!{any}"); }
		@Test public void test_145() { testInvalid("!int","!{int}"); }
		@Test public void test_146() { testInvalid("!int","!!any"); }
		@Test public void test_147() { testInvalid("!int","!!int"); }
		@Test public void test_148() { testValid("!int","{{{any}}}"); }
		@Test public void test_149() { testValid("!int","{{{int}}}"); }
		@Test public void test_150() { testValid("!int","{{!int}}"); }
		@Test public void test_151() { testValid("!int","{!{any}}"); }
		@Test public void test_152() { testValid("!int","{!{int}}"); }
		@Test public void test_153() { testValid("!int","{!!any}"); }
		@Test public void test_154() { testValid("!int","{!!int}"); }
		@Test public void test_155() { testInvalid("!int","!{{any}}"); }
		@Test public void test_156() { testInvalid("!int","!{{int}}"); }
		@Test public void test_157() { testInvalid("!int","!{!int}"); }
		@Test public void test_158() { testValid("!int","!!{any}"); }
		@Test public void test_159() { testValid("!int","!!{int}"); }
		@Test public void test_160() { testValid("!int","!!!any"); }
		@Test public void test_161() { testValid("!int","!!!int"); }
		@Test public void test_162() { testInvalid("{{any}}","any"); }
		@Test public void test_163() { testInvalid("{{any}}","int"); }
		@Test public void test_164() { testInvalid("{{any}}","{any}"); }
		@Test public void test_165() { testInvalid("{{any}}","{int}"); }
		@Test public void test_166() { testValid("{{any}}","!any"); }
		@Test public void test_167() { testInvalid("{{any}}","!int"); }
		@Test public void test_168() { testValid("{{any}}","{{any}}"); }
		@Test public void test_169() { testValid("{{any}}","{{int}}"); }
		@Test public void test_170() { testInvalid("{{any}}","{!int}"); }
		@Test public void test_171() { testInvalid("{{any}}","!{any}"); }
		@Test public void test_172() { testInvalid("{{any}}","!{int}"); }
		@Test public void test_173() { testInvalid("{{any}}","!!any"); }
		@Test public void test_174() { testInvalid("{{any}}","!!int"); }
		@Test public void test_175() { testValid("{{any}}","{{{any}}}"); }
		@Test public void test_176() { testValid("{{any}}","{{{int}}}"); }
		@Test public void test_177() { testValid("{{any}}","{{!int}}"); }
		@Test public void test_178() { testInvalid("{{any}}","{!{any}}"); }
		@Test public void test_179() { testInvalid("{{any}}","{!{int}}"); }
		@Test public void test_180() { testInvalid("{{any}}","{!!any}"); }
		@Test public void test_181() { testInvalid("{{any}}","{!!int}"); }
		@Test public void test_182() { testInvalid("{{any}}","!{{any}}"); }
		@Test public void test_183() { testInvalid("{{any}}","!{{int}}"); }
		@Test public void test_184() { testInvalid("{{any}}","!{!int}"); }
		@Test public void test_185() { testInvalid("{{any}}","!!{any}"); }
		@Test public void test_186() { testInvalid("{{any}}","!!{int}"); }
		@Test public void test_187() { testValid("{{any}}","!!!any"); }
		@Test public void test_188() { testInvalid("{{any}}","!!!int"); }
		@Test public void test_189() { testInvalid("{{int}}","any"); }
		@Test public void test_190() { testInvalid("{{int}}","int"); }
		@Test public void test_191() { testInvalid("{{int}}","{any}"); }
		@Test public void test_192() { testInvalid("{{int}}","{int}"); }
		@Test public void test_193() { testValid("{{int}}","!any"); }
		@Test public void test_194() { testInvalid("{{int}}","!int"); }
		@Test public void test_195() { testInvalid("{{int}}","{{any}}"); }
		@Test public void test_196() { testValid("{{int}}","{{int}}"); }
		@Test public void test_197() { testInvalid("{{int}}","{!int}"); }
		@Test public void test_198() { testInvalid("{{int}}","!{any}"); }
		@Test public void test_199() { testInvalid("{{int}}","!{int}"); }
		@Test public void test_200() { testInvalid("{{int}}","!!any"); }
		@Test public void test_201() { testInvalid("{{int}}","!!int"); }
		@Test public void test_202() { testInvalid("{{int}}","{{{any}}}"); }
		@Test public void test_203() { testInvalid("{{int}}","{{{int}}}"); }
		@Test public void test_204() { testInvalid("{{int}}","{{!int}}"); }
		@Test public void test_205() { testInvalid("{{int}}","{!{any}}"); }
		@Test public void test_206() { testInvalid("{{int}}","{!{int}}"); }
		@Test public void test_207() { testInvalid("{{int}}","{!!any}"); }
		@Test public void test_208() { testInvalid("{{int}}","{!!int}"); }
		@Test public void test_209() { testInvalid("{{int}}","!{{any}}"); }
		@Test public void test_210() { testInvalid("{{int}}","!{{int}}"); }
		@Test public void test_211() { testInvalid("{{int}}","!{!int}"); }
		@Test public void test_212() { testInvalid("{{int}}","!!{any}"); }
		@Test public void test_213() { testInvalid("{{int}}","!!{int}"); }
		@Test public void test_214() { testValid("{{int}}","!!!any"); }
		@Test public void test_215() { testInvalid("{{int}}","!!!int"); }
		@Test public void test_216() { testInvalid("{!int}","any"); }
		@Test public void test_217() { testInvalid("{!int}","int"); }
		@Test public void test_218() { testInvalid("{!int}","{any}"); }
		@Test public void test_219() { testInvalid("{!int}","{int}"); }
		@Test public void test_220() { testValid("{!int}","!any"); }
		@Test public void test_221() { testInvalid("{!int}","!int"); }
		@Test public void test_222() { testValid("{!int}","{{any}}"); }
		@Test public void test_223() { testValid("{!int}","{{int}}"); }
		@Test public void test_224() { testValid("{!int}","{!int}"); }
		@Test public void test_225() { testInvalid("{!int}","!{any}"); }
		@Test public void test_226() { testInvalid("{!int}","!{int}"); }
		@Test public void test_227() { testInvalid("{!int}","!!any"); }
		@Test public void test_228() { testInvalid("{!int}","!!int"); }
		@Test public void test_229() { testValid("{!int}","{{{any}}}"); }
		@Test public void test_230() { testValid("{!int}","{{{int}}}"); }
		@Test public void test_231() { testValid("{!int}","{{!int}}"); }
		@Test public void test_232() { testInvalid("{!int}","{!{any}}"); }
		@Test public void test_233() { testInvalid("{!int}","{!{int}}"); }
		@Test public void test_234() { testInvalid("{!int}","{!!any}"); }
		@Test public void test_235() { testInvalid("{!int}","{!!int}"); }
		@Test public void test_236() { testInvalid("{!int}","!{{any}}"); }
		@Test public void test_237() { testInvalid("{!int}","!{{int}}"); }
		@Test public void test_238() { testInvalid("{!int}","!{!int}"); }
		@Test public void test_239() { testInvalid("{!int}","!!{any}"); }
		@Test public void test_240() { testInvalid("{!int}","!!{int}"); }
		@Test public void test_241() { testValid("{!int}","!!!any"); }
		@Test public void test_242() { testInvalid("{!int}","!!!int"); }
		@Test public void test_243() { testInvalid("!{any}","any"); }
		@Test public void test_244() { testValid("!{any}","int"); }
		@Test public void test_245() { testInvalid("!{any}","{any}"); }
		@Test public void test_246() { testInvalid("!{any}","{int}"); }
		@Test public void test_247() { testValid("!{any}","!any"); }
		@Test public void test_248() { testInvalid("!{any}","!int"); }
		@Test public void test_249() { testInvalid("!{any}","{{any}}"); }
		@Test public void test_250() { testInvalid("!{any}","{{int}}"); }
		@Test public void test_251() { testInvalid("!{any}","{!int}"); }
		@Test public void test_252() { testValid("!{any}","!{any}"); }
		@Test public void test_253() { testInvalid("!{any}","!{int}"); }
		@Test public void test_254() { testInvalid("!{any}","!!any"); }
		@Test public void test_255() { testValid("!{any}","!!int"); }
		@Test public void test_256() { testInvalid("!{any}","{{{any}}}"); }
		@Test public void test_257() { testInvalid("!{any}","{{{int}}}"); }
		@Test public void test_258() { testInvalid("!{any}","{{!int}}"); }
		@Test public void test_259() { testInvalid("!{any}","{!{any}}"); }
		@Test public void test_260() { testInvalid("!{any}","{!{int}}"); }
		@Test public void test_261() { testInvalid("!{any}","{!!any}"); }
		@Test public void test_262() { testInvalid("!{any}","{!!int}"); }
		@Test public void test_263() { testInvalid("!{any}","!{{any}}"); }
		@Test public void test_264() { testInvalid("!{any}","!{{int}}"); }
		@Test public void test_265() { testInvalid("!{any}","!{!int}"); }
		@Test public void test_266() { testInvalid("!{any}","!!{any}"); }
		@Test public void test_267() { testInvalid("!{any}","!!{int}"); }
		@Test public void test_268() { testValid("!{any}","!!!any"); }
		@Test public void test_269() { testInvalid("!{any}","!!!int"); }
		@Test public void test_270() { testInvalid("!{int}","any"); }
		@Test public void test_271() { testValid("!{int}","int"); }
		@Test public void test_272() { testInvalid("!{int}","{any}"); }
		@Test public void test_273() { testInvalid("!{int}","{int}"); }
		@Test public void test_274() { testValid("!{int}","!any"); }
		@Test public void test_275() { testInvalid("!{int}","!int"); }
		@Test public void test_276() { testValid("!{int}","{{any}}"); }
		@Test public void test_277() { testValid("!{int}","{{int}}"); }
		@Test public void test_278() { testValid("!{int}","{!int}"); }
		@Test public void test_279() { testValid("!{int}","!{any}"); }
		@Test public void test_280() { testValid("!{int}","!{int}"); }
		@Test public void test_281() { testInvalid("!{int}","!!any"); }
		@Test public void test_282() { testValid("!{int}","!!int"); }
		@Test public void test_283() { testValid("!{int}","{{{any}}}"); }
		@Test public void test_284() { testValid("!{int}","{{{int}}}"); }
		@Test public void test_285() { testValid("!{int}","{{!int}}"); }
		@Test public void test_286() { testInvalid("!{int}","{!{any}}"); }
		@Test public void test_287() { testInvalid("!{int}","{!{int}}"); }
		@Test public void test_288() { testInvalid("!{int}","{!!any}"); }
		@Test public void test_289() { testInvalid("!{int}","{!!int}"); }
		@Test public void test_290() { testInvalid("!{int}","!{{any}}"); }
		@Test public void test_291() { testInvalid("!{int}","!{{int}}"); }
		@Test public void test_292() { testInvalid("!{int}","!{!int}"); }
		@Test public void test_293() { testInvalid("!{int}","!!{any}"); }
		@Test public void test_294() { testInvalid("!{int}","!!{int}"); }
		@Test public void test_295() { testValid("!{int}","!!!any"); }
		@Test public void test_296() { testInvalid("!{int}","!!!int"); }
		@Test public void test_297() { testValid("!!any","any"); }
		@Test public void test_298() { testValid("!!any","int"); }
		@Test public void test_299() { testValid("!!any","{any}"); }
		@Test public void test_300() { testValid("!!any","{int}"); }
		@Test public void test_301() { testValid("!!any","!any"); }
		@Test public void test_302() { testValid("!!any","!int"); }
		@Test public void test_303() { testValid("!!any","{{any}}"); }
		@Test public void test_304() { testValid("!!any","{{int}}"); }
		@Test public void test_305() { testValid("!!any","{!int}"); }
		@Test public void test_306() { testValid("!!any","!{any}"); }
		@Test public void test_307() { testValid("!!any","!{int}"); }
		@Test public void test_308() { testValid("!!any","!!any"); }
		@Test public void test_309() { testValid("!!any","!!int"); }
		@Test public void test_310() { testValid("!!any","{{{any}}}"); }
		@Test public void test_311() { testValid("!!any","{{{int}}}"); }
		@Test public void test_312() { testValid("!!any","{{!int}}"); }
		@Test public void test_313() { testValid("!!any","{!{any}}"); }
		@Test public void test_314() { testValid("!!any","{!{int}}"); }
		@Test public void test_315() { testValid("!!any","{!!any}"); }
		@Test public void test_316() { testValid("!!any","{!!int}"); }
		@Test public void test_317() { testValid("!!any","!{{any}}"); }
		@Test public void test_318() { testValid("!!any","!{{int}}"); }
		@Test public void test_319() { testValid("!!any","!{!int}"); }
		@Test public void test_320() { testValid("!!any","!!{any}"); }
		@Test public void test_321() { testValid("!!any","!!{int}"); }
		@Test public void test_322() { testValid("!!any","!!!any"); }
		@Test public void test_323() { testValid("!!any","!!!int"); }
		@Test public void test_324() { testInvalid("!!int","any"); }
		@Test public void test_325() { testValid("!!int","int"); }
		@Test public void test_326() { testInvalid("!!int","{any}"); }
		@Test public void test_327() { testInvalid("!!int","{int}"); }
		@Test public void test_328() { testValid("!!int","!any"); }
		@Test public void test_329() { testInvalid("!!int","!int"); }
		@Test public void test_330() { testInvalid("!!int","{{any}}"); }
		@Test public void test_331() { testInvalid("!!int","{{int}}"); }
		@Test public void test_332() { testInvalid("!!int","{!int}"); }
		@Test public void test_333() { testInvalid("!!int","!{any}"); }
		@Test public void test_334() { testInvalid("!!int","!{int}"); }
		@Test public void test_335() { testInvalid("!!int","!!any"); }
		@Test public void test_336() { testValid("!!int","!!int"); }
		@Test public void test_337() { testInvalid("!!int","{{{any}}}"); }
		@Test public void test_338() { testInvalid("!!int","{{{int}}}"); }
		@Test public void test_339() { testInvalid("!!int","{{!int}}"); }
		@Test public void test_340() { testInvalid("!!int","{!{any}}"); }
		@Test public void test_341() { testInvalid("!!int","{!{int}}"); }
		@Test public void test_342() { testInvalid("!!int","{!!any}"); }
		@Test public void test_343() { testInvalid("!!int","{!!int}"); }
		@Test public void test_344() { testInvalid("!!int","!{{any}}"); }
		@Test public void test_345() { testInvalid("!!int","!{{int}}"); }
		@Test public void test_346() { testInvalid("!!int","!{!int}"); }
		@Test public void test_347() { testInvalid("!!int","!!{any}"); }
		@Test public void test_348() { testInvalid("!!int","!!{int}"); }
		@Test public void test_349() { testValid("!!int","!!!any"); }
		@Test public void test_350() { testInvalid("!!int","!!!int"); }
		@Test public void test_351() { testInvalid("{{{any}}}","any"); }
		@Test public void test_352() { testInvalid("{{{any}}}","int"); }
		@Test public void test_353() { testInvalid("{{{any}}}","{any}"); }
		@Test public void test_354() { testInvalid("{{{any}}}","{int}"); }
		@Test public void test_355() { testValid("{{{any}}}","!any"); }
		@Test public void test_356() { testInvalid("{{{any}}}","!int"); }
		@Test public void test_357() { testInvalid("{{{any}}}","{{any}}"); }
		@Test public void test_358() { testInvalid("{{{any}}}","{{int}}"); }
		@Test public void test_359() { testInvalid("{{{any}}}","{!int}"); }
		@Test public void test_360() { testInvalid("{{{any}}}","!{any}"); }
		@Test public void test_361() { testInvalid("{{{any}}}","!{int}"); }
		@Test public void test_362() { testInvalid("{{{any}}}","!!any"); }
		@Test public void test_363() { testInvalid("{{{any}}}","!!int"); }
		@Test public void test_364() { testValid("{{{any}}}","{{{any}}}"); }
		@Test public void test_365() { testValid("{{{any}}}","{{{int}}}"); }
		@Test public void test_366() { testInvalid("{{{any}}}","{{!int}}"); }
		@Test public void test_367() { testInvalid("{{{any}}}","{!{any}}"); }
		@Test public void test_368() { testInvalid("{{{any}}}","{!{int}}"); }
		@Test public void test_369() { testInvalid("{{{any}}}","{!!any}"); }
		@Test public void test_370() { testInvalid("{{{any}}}","{!!int}"); }
		@Test public void test_371() { testInvalid("{{{any}}}","!{{any}}"); }
		@Test public void test_372() { testInvalid("{{{any}}}","!{{int}}"); }
		@Test public void test_373() { testInvalid("{{{any}}}","!{!int}"); }
		@Test public void test_374() { testInvalid("{{{any}}}","!!{any}"); }
		@Test public void test_375() { testInvalid("{{{any}}}","!!{int}"); }
		@Test public void test_376() { testValid("{{{any}}}","!!!any"); }
		@Test public void test_377() { testInvalid("{{{any}}}","!!!int"); }
		@Test public void test_378() { testInvalid("{{{int}}}","any"); }
		@Test public void test_379() { testInvalid("{{{int}}}","int"); }
		@Test public void test_380() { testInvalid("{{{int}}}","{any}"); }
		@Test public void test_381() { testInvalid("{{{int}}}","{int}"); }
		@Test public void test_382() { testValid("{{{int}}}","!any"); }
		@Test public void test_383() { testInvalid("{{{int}}}","!int"); }
		@Test public void test_384() { testInvalid("{{{int}}}","{{any}}"); }
		@Test public void test_385() { testInvalid("{{{int}}}","{{int}}"); }
		@Test public void test_386() { testInvalid("{{{int}}}","{!int}"); }
		@Test public void test_387() { testInvalid("{{{int}}}","!{any}"); }
		@Test public void test_388() { testInvalid("{{{int}}}","!{int}"); }
		@Test public void test_389() { testInvalid("{{{int}}}","!!any"); }
		@Test public void test_390() { testInvalid("{{{int}}}","!!int"); }
		@Test public void test_391() { testInvalid("{{{int}}}","{{{any}}}"); }
		@Test public void test_392() { testValid("{{{int}}}","{{{int}}}"); }
		@Test public void test_393() { testInvalid("{{{int}}}","{{!int}}"); }
		@Test public void test_394() { testInvalid("{{{int}}}","{!{any}}"); }
		@Test public void test_395() { testInvalid("{{{int}}}","{!{int}}"); }
		@Test public void test_396() { testInvalid("{{{int}}}","{!!any}"); }
		@Test public void test_397() { testInvalid("{{{int}}}","{!!int}"); }
		@Test public void test_398() { testInvalid("{{{int}}}","!{{any}}"); }
		@Test public void test_399() { testInvalid("{{{int}}}","!{{int}}"); }
		@Test public void test_400() { testInvalid("{{{int}}}","!{!int}"); }
		@Test public void test_401() { testInvalid("{{{int}}}","!!{any}"); }
		@Test public void test_402() { testInvalid("{{{int}}}","!!{int}"); }
		@Test public void test_403() { testValid("{{{int}}}","!!!any"); }
		@Test public void test_404() { testInvalid("{{{int}}}","!!!int"); }
		@Test public void test_405() { testInvalid("{{!int}}","any"); }
		@Test public void test_406() { testInvalid("{{!int}}","int"); }
		@Test public void test_407() { testInvalid("{{!int}}","{any}"); }
		@Test public void test_408() { testInvalid("{{!int}}","{int}"); }
		@Test public void test_409() { testValid("{{!int}}","!any"); }
		@Test public void test_410() { testInvalid("{{!int}}","!int"); }
		@Test public void test_411() { testInvalid("{{!int}}","{{any}}"); }
		@Test public void test_412() { testInvalid("{{!int}}","{{int}}"); }
		@Test public void test_413() { testInvalid("{{!int}}","{!int}"); }
		@Test public void test_414() { testInvalid("{{!int}}","!{any}"); }
		@Test public void test_415() { testInvalid("{{!int}}","!{int}"); }
		@Test public void test_416() { testInvalid("{{!int}}","!!any"); }
		@Test public void test_417() { testInvalid("{{!int}}","!!int"); }
		@Test public void test_418() { testValid("{{!int}}","{{{any}}}"); }
		@Test public void test_419() { testValid("{{!int}}","{{{int}}}"); }
		@Test public void test_420() { testValid("{{!int}}","{{!int}}"); }
		@Test public void test_421() { testInvalid("{{!int}}","{!{any}}"); }
		@Test public void test_422() { testInvalid("{{!int}}","{!{int}}"); }
		@Test public void test_423() { testInvalid("{{!int}}","{!!any}"); }
		@Test public void test_424() { testInvalid("{{!int}}","{!!int}"); }
		@Test public void test_425() { testInvalid("{{!int}}","!{{any}}"); }
		@Test public void test_426() { testInvalid("{{!int}}","!{{int}}"); }
		@Test public void test_427() { testInvalid("{{!int}}","!{!int}"); }
		@Test public void test_428() { testInvalid("{{!int}}","!!{any}"); }
		@Test public void test_429() { testInvalid("{{!int}}","!!{int}"); }
		@Test public void test_430() { testValid("{{!int}}","!!!any"); }
		@Test public void test_431() { testInvalid("{{!int}}","!!!int"); }
		@Test public void test_432() { testInvalid("{!{any}}","any"); }
		@Test public void test_433() { testInvalid("{!{any}}","int"); }
		@Test public void test_434() { testInvalid("{!{any}}","{any}"); }
		@Test public void test_435() { testValid("{!{any}}","{int}"); }
		@Test public void test_436() { testValid("{!{any}}","!any"); }
		@Test public void test_437() { testInvalid("{!{any}}","!int"); }
		@Test public void test_438() { testInvalid("{!{any}}","{{any}}"); }
		@Test public void test_439() { testInvalid("{!{any}}","{{int}}"); }
		@Test public void test_440() { testInvalid("{!{any}}","{!int}"); }
		@Test public void test_441() { testInvalid("{!{any}}","!{any}"); }
		@Test public void test_442() { testInvalid("{!{any}}","!{int}"); }
		@Test public void test_443() { testInvalid("{!{any}}","!!any"); }
		@Test public void test_444() { testInvalid("{!{any}}","!!int"); }
		@Test public void test_445() { testInvalid("{!{any}}","{{{any}}}"); }
		@Test public void test_446() { testInvalid("{!{any}}","{{{int}}}"); }
		@Test public void test_447() { testInvalid("{!{any}}","{{!int}}"); }
		@Test public void test_448() { testValid("{!{any}}","{!{any}}"); }
		@Test public void test_449() { testInvalid("{!{any}}","{!{int}}"); }
		@Test public void test_450() { testInvalid("{!{any}}","{!!any}"); }
		@Test public void test_451() { testValid("{!{any}}","{!!int}"); }
		@Test public void test_452() { testInvalid("{!{any}}","!{{any}}"); }
		@Test public void test_453() { testInvalid("{!{any}}","!{{int}}"); }
		@Test public void test_454() { testInvalid("{!{any}}","!{!int}"); }
		@Test public void test_455() { testInvalid("{!{any}}","!!{any}"); }
		@Test public void test_456() { testValid("{!{any}}","!!{int}"); }
		@Test public void test_457() { testValid("{!{any}}","!!!any"); }
		@Test public void test_458() { testInvalid("{!{any}}","!!!int"); }
		@Test public void test_459() { testInvalid("{!{int}}","any"); }
		@Test public void test_460() { testInvalid("{!{int}}","int"); }
		@Test public void test_461() { testInvalid("{!{int}}","{any}"); }
		@Test public void test_462() { testValid("{!{int}}","{int}"); }
		@Test public void test_463() { testValid("{!{int}}","!any"); }
		@Test public void test_464() { testInvalid("{!{int}}","!int"); }
		@Test public void test_465() { testInvalid("{!{int}}","{{any}}"); }
		@Test public void test_466() { testInvalid("{!{int}}","{{int}}"); }
		@Test public void test_467() { testInvalid("{!{int}}","{!int}"); }
		@Test public void test_468() { testInvalid("{!{int}}","!{any}"); }
		@Test public void test_469() { testInvalid("{!{int}}","!{int}"); }
		@Test public void test_470() { testInvalid("{!{int}}","!!any"); }
		@Test public void test_471() { testInvalid("{!{int}}","!!int"); }
		@Test public void test_472() { testValid("{!{int}}","{{{any}}}"); }
		@Test public void test_473() { testValid("{!{int}}","{{{int}}}"); }
		@Test public void test_474() { testValid("{!{int}}","{{!int}}"); }
		@Test public void test_475() { testValid("{!{int}}","{!{any}}"); }
		@Test public void test_476() { testValid("{!{int}}","{!{int}}"); }
		@Test public void test_477() { testInvalid("{!{int}}","{!!any}"); }
		@Test public void test_478() { testValid("{!{int}}","{!!int}"); }
		@Test public void test_479() { testInvalid("{!{int}}","!{{any}}"); }
		@Test public void test_480() { testInvalid("{!{int}}","!{{int}}"); }
		@Test public void test_481() { testInvalid("{!{int}}","!{!int}"); }
		@Test public void test_482() { testInvalid("{!{int}}","!!{any}"); }
		@Test public void test_483() { testValid("{!{int}}","!!{int}"); }
		@Test public void test_484() { testValid("{!{int}}","!!!any"); }
		@Test public void test_485() { testInvalid("{!{int}}","!!!int"); }
		@Test public void test_486() { testInvalid("{!!any}","any"); }
		@Test public void test_487() { testInvalid("{!!any}","int"); }
		@Test public void test_488() { testValid("{!!any}","{any}"); }
		@Test public void test_489() { testValid("{!!any}","{int}"); }
		@Test public void test_490() { testValid("{!!any}","!any"); }
		@Test public void test_491() { testInvalid("{!!any}","!int"); }
		@Test public void test_492() { testValid("{!!any}","{{any}}"); }
		@Test public void test_493() { testValid("{!!any}","{{int}}"); }
		@Test public void test_494() { testValid("{!!any}","{!int}"); }
		@Test public void test_495() { testInvalid("{!!any}","!{any}"); }
		@Test public void test_496() { testInvalid("{!!any}","!{int}"); }
		@Test public void test_497() { testInvalid("{!!any}","!!any"); }
		@Test public void test_498() { testInvalid("{!!any}","!!int"); }
		@Test public void test_499() { testValid("{!!any}","{{{any}}}"); }
		@Test public void test_500() { testValid("{!!any}","{{{int}}}"); }
		@Test public void test_501() { testValid("{!!any}","{{!int}}"); }
		@Test public void test_502() { testValid("{!!any}","{!{any}}"); }
		@Test public void test_503() { testValid("{!!any}","{!{int}}"); }
		@Test public void test_504() { testValid("{!!any}","{!!any}"); }
		@Test public void test_505() { testValid("{!!any}","{!!int}"); }
		@Test public void test_506() { testInvalid("{!!any}","!{{any}}"); }
		@Test public void test_507() { testInvalid("{!!any}","!{{int}}"); }
		@Test public void test_508() { testInvalid("{!!any}","!{!int}"); }
		@Test public void test_509() { testValid("{!!any}","!!{any}"); }
		@Test public void test_510() { testValid("{!!any}","!!{int}"); }
		@Test public void test_511() { testValid("{!!any}","!!!any"); }
		@Test public void test_512() { testInvalid("{!!any}","!!!int"); }
		@Test public void test_513() { testInvalid("{!!int}","any"); }
		@Test public void test_514() { testInvalid("{!!int}","int"); }
		@Test public void test_515() { testInvalid("{!!int}","{any}"); }
		@Test public void test_516() { testValid("{!!int}","{int}"); }
		@Test public void test_517() { testValid("{!!int}","!any"); }
		@Test public void test_518() { testInvalid("{!!int}","!int"); }
		@Test public void test_519() { testInvalid("{!!int}","{{any}}"); }
		@Test public void test_520() { testInvalid("{!!int}","{{int}}"); }
		@Test public void test_521() { testInvalid("{!!int}","{!int}"); }
		@Test public void test_522() { testInvalid("{!!int}","!{any}"); }
		@Test public void test_523() { testInvalid("{!!int}","!{int}"); }
		@Test public void test_524() { testInvalid("{!!int}","!!any"); }
		@Test public void test_525() { testInvalid("{!!int}","!!int"); }
		@Test public void test_526() { testInvalid("{!!int}","{{{any}}}"); }
		@Test public void test_527() { testInvalid("{!!int}","{{{int}}}"); }
		@Test public void test_528() { testInvalid("{!!int}","{{!int}}"); }
		@Test public void test_529() { testInvalid("{!!int}","{!{any}}"); }
		@Test public void test_530() { testInvalid("{!!int}","{!{int}}"); }
		@Test public void test_531() { testInvalid("{!!int}","{!!any}"); }
		@Test public void test_532() { testValid("{!!int}","{!!int}"); }
		@Test public void test_533() { testInvalid("{!!int}","!{{any}}"); }
		@Test public void test_534() { testInvalid("{!!int}","!{{int}}"); }
		@Test public void test_535() { testInvalid("{!!int}","!{!int}"); }
		@Test public void test_536() { testInvalid("{!!int}","!!{any}"); }
		@Test public void test_537() { testValid("{!!int}","!!{int}"); }
		@Test public void test_538() { testValid("{!!int}","!!!any"); }
		@Test public void test_539() { testInvalid("{!!int}","!!!int"); }
		@Test public void test_540() { testInvalid("!{{any}}","any"); }
		@Test public void test_541() { testValid("!{{any}}","int"); }
		@Test public void test_542() { testInvalid("!{{any}}","{any}"); }
		@Test public void test_543() { testValid("!{{any}}","{int}"); }
		@Test public void test_544() { testValid("!{{any}}","!any"); }
		@Test public void test_545() { testInvalid("!{{any}}","!int"); }
		@Test public void test_546() { testInvalid("!{{any}}","{{any}}"); }
		@Test public void test_547() { testInvalid("!{{any}}","{{int}}"); }
		@Test public void test_548() { testInvalid("!{{any}}","{!int}"); }
		@Test public void test_549() { testValid("!{{any}}","!{any}"); }
		@Test public void test_550() { testInvalid("!{{any}}","!{int}"); }
		@Test public void test_551() { testInvalid("!{{any}}","!!any"); }
		@Test public void test_552() { testValid("!{{any}}","!!int"); }
		@Test public void test_553() { testInvalid("!{{any}}","{{{any}}}"); }
		@Test public void test_554() { testInvalid("!{{any}}","{{{int}}}"); }
		@Test public void test_555() { testInvalid("!{{any}}","{{!int}}"); }
		@Test public void test_556() { testValid("!{{any}}","{!{any}}"); }
		@Test public void test_557() { testInvalid("!{{any}}","{!{int}}"); }
		@Test public void test_558() { testInvalid("!{{any}}","{!!any}"); }
		@Test public void test_559() { testValid("!{{any}}","{!!int}"); }
		@Test public void test_560() { testValid("!{{any}}","!{{any}}"); }
		@Test public void test_561() { testInvalid("!{{any}}","!{{int}}"); }
		@Test public void test_562() { testValid("!{{any}}","!{!int}"); }
		@Test public void test_563() { testInvalid("!{{any}}","!!{any}"); }
		@Test public void test_564() { testValid("!{{any}}","!!{int}"); }
		@Test public void test_565() { testValid("!{{any}}","!!!any"); }
		@Test public void test_566() { testInvalid("!{{any}}","!!!int"); }
		@Test public void test_567() { testInvalid("!{{int}}","any"); }
		@Test public void test_568() { testValid("!{{int}}","int"); }
		@Test public void test_569() { testInvalid("!{{int}}","{any}"); }
		@Test public void test_570() { testValid("!{{int}}","{int}"); }
		@Test public void test_571() { testValid("!{{int}}","!any"); }
		@Test public void test_572() { testInvalid("!{{int}}","!int"); }
		@Test public void test_573() { testInvalid("!{{int}}","{{any}}"); }
		@Test public void test_574() { testInvalid("!{{int}}","{{int}}"); }
		@Test public void test_575() { testInvalid("!{{int}}","{!int}"); }
		@Test public void test_576() { testValid("!{{int}}","!{any}"); }
		@Test public void test_577() { testInvalid("!{{int}}","!{int}"); }
		@Test public void test_578() { testInvalid("!{{int}}","!!any"); }
		@Test public void test_579() { testValid("!{{int}}","!!int"); }
		@Test public void test_580() { testValid("!{{int}}","{{{any}}}"); }
		@Test public void test_581() { testValid("!{{int}}","{{{int}}}"); }
		@Test public void test_582() { testValid("!{{int}}","{{!int}}"); }
		@Test public void test_583() { testValid("!{{int}}","{!{any}}"); }
		@Test public void test_584() { testValid("!{{int}}","{!{int}}"); }
		@Test public void test_585() { testInvalid("!{{int}}","{!!any}"); }
		@Test public void test_586() { testValid("!{{int}}","{!!int}"); }
		@Test public void test_587() { testValid("!{{int}}","!{{any}}"); }
		@Test public void test_588() { testValid("!{{int}}","!{{int}}"); }
		@Test public void test_589() { testValid("!{{int}}","!{!int}"); }
		@Test public void test_590() { testInvalid("!{{int}}","!!{any}"); }
		@Test public void test_591() { testValid("!{{int}}","!!{int}"); }
		@Test public void test_592() { testValid("!{{int}}","!!!any"); }
		@Test public void test_593() { testInvalid("!{{int}}","!!!int"); }
		@Test public void test_594() { testInvalid("!{!int}","any"); }
		@Test public void test_595() { testValid("!{!int}","int"); }
		@Test public void test_596() { testInvalid("!{!int}","{any}"); }
		@Test public void test_597() { testValid("!{!int}","{int}"); }
		@Test public void test_598() { testValid("!{!int}","!any"); }
		@Test public void test_599() { testInvalid("!{!int}","!int"); }
		@Test public void test_600() { testInvalid("!{!int}","{{any}}"); }
		@Test public void test_601() { testInvalid("!{!int}","{{int}}"); }
		@Test public void test_602() { testInvalid("!{!int}","{!int}"); }
		@Test public void test_603() { testValid("!{!int}","!{any}"); }
		@Test public void test_604() { testInvalid("!{!int}","!{int}"); }
		@Test public void test_605() { testInvalid("!{!int}","!!any"); }
		@Test public void test_606() { testValid("!{!int}","!!int"); }
		@Test public void test_607() { testInvalid("!{!int}","{{{any}}}"); }
		@Test public void test_608() { testInvalid("!{!int}","{{{int}}}"); }
		@Test public void test_609() { testInvalid("!{!int}","{{!int}}"); }
		@Test public void test_610() { testInvalid("!{!int}","{!{any}}"); }
		@Test public void test_611() { testInvalid("!{!int}","{!{int}}"); }
		@Test public void test_612() { testInvalid("!{!int}","{!!any}"); }
		@Test public void test_613() { testValid("!{!int}","{!!int}"); }
		@Test public void test_614() { testInvalid("!{!int}","!{{any}}"); }
		@Test public void test_615() { testInvalid("!{!int}","!{{int}}"); }
		@Test public void test_616() { testValid("!{!int}","!{!int}"); }
		@Test public void test_617() { testInvalid("!{!int}","!!{any}"); }
		@Test public void test_618() { testValid("!{!int}","!!{int}"); }
		@Test public void test_619() { testValid("!{!int}","!!!any"); }
		@Test public void test_620() { testInvalid("!{!int}","!!!int"); }
		@Test public void test_621() { testInvalid("!!{any}","any"); }
		@Test public void test_622() { testInvalid("!!{any}","int"); }
		@Test public void test_623() { testValid("!!{any}","{any}"); }
		@Test public void test_624() { testValid("!!{any}","{int}"); }
		@Test public void test_625() { testValid("!!{any}","!any"); }
		@Test public void test_626() { testInvalid("!!{any}","!int"); }
		@Test public void test_627() { testValid("!!{any}","{{any}}"); }
		@Test public void test_628() { testValid("!!{any}","{{int}}"); }
		@Test public void test_629() { testValid("!!{any}","{!int}"); }
		@Test public void test_630() { testInvalid("!!{any}","!{any}"); }
		@Test public void test_631() { testInvalid("!!{any}","!{int}"); }
		@Test public void test_632() { testInvalid("!!{any}","!!any"); }
		@Test public void test_633() { testInvalid("!!{any}","!!int"); }
		@Test public void test_634() { testValid("!!{any}","{{{any}}}"); }
		@Test public void test_635() { testValid("!!{any}","{{{int}}}"); }
		@Test public void test_636() { testValid("!!{any}","{{!int}}"); }
		@Test public void test_637() { testValid("!!{any}","{!{any}}"); }
		@Test public void test_638() { testValid("!!{any}","{!{int}}"); }
		@Test public void test_639() { testValid("!!{any}","{!!any}"); }
		@Test public void test_640() { testValid("!!{any}","{!!int}"); }
		@Test public void test_641() { testInvalid("!!{any}","!{{any}}"); }
		@Test public void test_642() { testInvalid("!!{any}","!{{int}}"); }
		@Test public void test_643() { testInvalid("!!{any}","!{!int}"); }
		@Test public void test_644() { testValid("!!{any}","!!{any}"); }
		@Test public void test_645() { testValid("!!{any}","!!{int}"); }
		@Test public void test_646() { testValid("!!{any}","!!!any"); }
		@Test public void test_647() { testInvalid("!!{any}","!!!int"); }
		@Test public void test_648() { testInvalid("!!{int}","any"); }
		@Test public void test_649() { testInvalid("!!{int}","int"); }
		@Test public void test_650() { testInvalid("!!{int}","{any}"); }
		@Test public void test_651() { testValid("!!{int}","{int}"); }
		@Test public void test_652() { testValid("!!{int}","!any"); }
		@Test public void test_653() { testInvalid("!!{int}","!int"); }
		@Test public void test_654() { testInvalid("!!{int}","{{any}}"); }
		@Test public void test_655() { testInvalid("!!{int}","{{int}}"); }
		@Test public void test_656() { testInvalid("!!{int}","{!int}"); }
		@Test public void test_657() { testInvalid("!!{int}","!{any}"); }
		@Test public void test_658() { testInvalid("!!{int}","!{int}"); }
		@Test public void test_659() { testInvalid("!!{int}","!!any"); }
		@Test public void test_660() { testInvalid("!!{int}","!!int"); }
		@Test public void test_661() { testInvalid("!!{int}","{{{any}}}"); }
		@Test public void test_662() { testInvalid("!!{int}","{{{int}}}"); }
		@Test public void test_663() { testInvalid("!!{int}","{{!int}}"); }
		@Test public void test_664() { testInvalid("!!{int}","{!{any}}"); }
		@Test public void test_665() { testInvalid("!!{int}","{!{int}}"); }
		@Test public void test_666() { testInvalid("!!{int}","{!!any}"); }
		@Test public void test_667() { testValid("!!{int}","{!!int}"); }
		@Test public void test_668() { testInvalid("!!{int}","!{{any}}"); }
		@Test public void test_669() { testInvalid("!!{int}","!{{int}}"); }
		@Test public void test_670() { testInvalid("!!{int}","!{!int}"); }
		@Test public void test_671() { testInvalid("!!{int}","!!{any}"); }
		@Test public void test_672() { testValid("!!{int}","!!{int}"); }
		@Test public void test_673() { testValid("!!{int}","!!!any"); }
		@Test public void test_674() { testInvalid("!!{int}","!!!int"); }
		@Test public void test_675() { testInvalid("!!!any","any"); }
		@Test public void test_676() { testInvalid("!!!any","int"); }
		@Test public void test_677() { testInvalid("!!!any","{any}"); }
		@Test public void test_678() { testInvalid("!!!any","{int}"); }
		@Test public void test_679() { testValid("!!!any","!any"); }
		@Test public void test_680() { testInvalid("!!!any","!int"); }
		@Test public void test_681() { testInvalid("!!!any","{{any}}"); }
		@Test public void test_682() { testInvalid("!!!any","{{int}}"); }
		@Test public void test_683() { testInvalid("!!!any","{!int}"); }
		@Test public void test_684() { testInvalid("!!!any","!{any}"); }
		@Test public void test_685() { testInvalid("!!!any","!{int}"); }
		@Test public void test_686() { testInvalid("!!!any","!!any"); }
		@Test public void test_687() { testInvalid("!!!any","!!int"); }
		@Test public void test_688() { testInvalid("!!!any","{{{any}}}"); }
		@Test public void test_689() { testInvalid("!!!any","{{{int}}}"); }
		@Test public void test_690() { testInvalid("!!!any","{{!int}}"); }
		@Test public void test_691() { testInvalid("!!!any","{!{any}}"); }
		@Test public void test_692() { testInvalid("!!!any","{!{int}}"); }
		@Test public void test_693() { testInvalid("!!!any","{!!any}"); }
		@Test public void test_694() { testInvalid("!!!any","{!!int}"); }
		@Test public void test_695() { testInvalid("!!!any","!{{any}}"); }
		@Test public void test_696() { testInvalid("!!!any","!{{int}}"); }
		@Test public void test_697() { testInvalid("!!!any","!{!int}"); }
		@Test public void test_698() { testInvalid("!!!any","!!{any}"); }
		@Test public void test_699() { testInvalid("!!!any","!!{int}"); }
		@Test public void test_700() { testValid("!!!any","!!!any"); }
		@Test public void test_701() { testInvalid("!!!any","!!!int"); }
		@Test public void test_702() { testInvalid("!!!int","any"); }
		@Test public void test_703() { testInvalid("!!!int","int"); }
		@Test public void test_704() { testValid("!!!int","{any}"); }
		@Test public void test_705() { testValid("!!!int","{int}"); }
		@Test public void test_706() { testValid("!!!int","!any"); }
		@Test public void test_707() { testValid("!!!int","!int"); }
		@Test public void test_708() { testValid("!!!int","{{any}}"); }
		@Test public void test_709() { testValid("!!!int","{{int}}"); }
		@Test public void test_710() { testValid("!!!int","{!int}"); }
		@Test public void test_711() { testInvalid("!!!int","!{any}"); }
		@Test public void test_712() { testInvalid("!!!int","!{int}"); }
		@Test public void test_713() { testInvalid("!!!int","!!any"); }
		@Test public void test_714() { testInvalid("!!!int","!!int"); }
		@Test public void test_715() { testValid("!!!int","{{{any}}}"); }
		@Test public void test_716() { testValid("!!!int","{{{int}}}"); }
		@Test public void test_717() { testValid("!!!int","{{!int}}"); }
		@Test public void test_718() { testValid("!!!int","{!{any}}"); }
		@Test public void test_719() { testValid("!!!int","{!{int}}"); }
		@Test public void test_720() { testValid("!!!int","{!!any}"); }
		@Test public void test_721() { testValid("!!!int","{!!int}"); }
		@Test public void test_722() { testInvalid("!!!int","!{{any}}"); }
		@Test public void test_723() { testInvalid("!!!int","!{{int}}"); }
		@Test public void test_724() { testInvalid("!!!int","!{!int}"); }
		@Test public void test_725() { testValid("!!!int","!!{any}"); }
		@Test public void test_726() { testValid("!!!int","!!{int}"); }
		@Test public void test_727() { testValid("!!!int","!!!any"); }
		@Test public void test_728() { testValid("!!!int","!!!int"); }
	}
}
