import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import org.junit.Test;
import types.testing.AbstractTestSuite;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class TestSuite_2_1 extends AbstractTestSuite {
	public static class Part_0 {
		@Test public void test_0() { testValid("any","any"); }
		@Test public void test_1() { testValid("any","int"); }
		@Test public void test_2() { testValid("any","{any}"); }
		@Test public void test_3() { testValid("any","{int}"); }
		@Test public void test_4() { testValid("any","!any"); }
		@Test public void test_5() { testValid("any","!int"); }
		@Test public void test_6() { testValid("any","{{any}}"); }
		@Test public void test_7() { testValid("any","{{int}}"); }
		@Test public void test_8() { testValid("any","{!int}"); }
		@Test public void test_9() { testValid("any","!{any}"); }
		@Test public void test_10() { testValid("any","!{int}"); }
		@Test public void test_11() { testValid("any","!!any"); }
		@Test public void test_12() { testValid("any","!!int"); }
		@Test public void test_13() { testInvalid("int","any"); }
		@Test public void test_14() { testValid("int","int"); }
		@Test public void test_15() { testInvalid("int","{any}"); }
		@Test public void test_16() { testInvalid("int","{int}"); }
		@Test public void test_17() { testValid("int","!any"); }
		@Test public void test_18() { testInvalid("int","!int"); }
		@Test public void test_19() { testInvalid("int","{{any}}"); }
		@Test public void test_20() { testInvalid("int","{{int}}"); }
		@Test public void test_21() { testInvalid("int","{!int}"); }
		@Test public void test_22() { testInvalid("int","!{any}"); }
		@Test public void test_23() { testInvalid("int","!{int}"); }
		@Test public void test_24() { testInvalid("int","!!any"); }
		@Test public void test_25() { testValid("int","!!int"); }
		@Test public void test_26() { testInvalid("{any}","any"); }
		@Test public void test_27() { testInvalid("{any}","int"); }
		@Test public void test_28() { testValid("{any}","{any}"); }
		@Test public void test_29() { testValid("{any}","{int}"); }
		@Test public void test_30() { testValid("{any}","!any"); }
		@Test public void test_31() { testInvalid("{any}","!int"); }
		@Test public void test_32() { testValid("{any}","{{any}}"); }
		@Test public void test_33() { testValid("{any}","{{int}}"); }
		@Test public void test_34() { testValid("{any}","{!int}"); }
		@Test public void test_35() { testInvalid("{any}","!{any}"); }
		@Test public void test_36() { testInvalid("{any}","!{int}"); }
		@Test public void test_37() { testInvalid("{any}","!!any"); }
		@Test public void test_38() { testInvalid("{any}","!!int"); }
		@Test public void test_39() { testInvalid("{int}","any"); }
		@Test public void test_40() { testInvalid("{int}","int"); }
		@Test public void test_41() { testInvalid("{int}","{any}"); }
		@Test public void test_42() { testValid("{int}","{int}"); }
		@Test public void test_43() { testValid("{int}","!any"); }
		@Test public void test_44() { testInvalid("{int}","!int"); }
		@Test public void test_45() { testInvalid("{int}","{{any}}"); }
		@Test public void test_46() { testInvalid("{int}","{{int}}"); }
		@Test public void test_47() { testInvalid("{int}","{!int}"); }
		@Test public void test_48() { testInvalid("{int}","!{any}"); }
		@Test public void test_49() { testInvalid("{int}","!{int}"); }
		@Test public void test_50() { testInvalid("{int}","!!any"); }
		@Test public void test_51() { testInvalid("{int}","!!int"); }
		@Test public void test_52() { testInvalid("!any","any"); }
		@Test public void test_53() { testInvalid("!any","int"); }
		@Test public void test_54() { testInvalid("!any","{any}"); }
		@Test public void test_55() { testInvalid("!any","{int}"); }
		@Test public void test_56() { testValid("!any","!any"); }
		@Test public void test_57() { testInvalid("!any","!int"); }
		@Test public void test_58() { testInvalid("!any","{{any}}"); }
		@Test public void test_59() { testInvalid("!any","{{int}}"); }
		@Test public void test_60() { testInvalid("!any","{!int}"); }
		@Test public void test_61() { testInvalid("!any","!{any}"); }
		@Test public void test_62() { testInvalid("!any","!{int}"); }
		@Test public void test_63() { testInvalid("!any","!!any"); }
		@Test public void test_64() { testInvalid("!any","!!int"); }
		@Test public void test_65() { testInvalid("!int","any"); }
		@Test public void test_66() { testInvalid("!int","int"); }
		@Test public void test_67() { testValid("!int","{any}"); }
		@Test public void test_68() { testValid("!int","{int}"); }
		@Test public void test_69() { testValid("!int","!any"); }
		@Test public void test_70() { testValid("!int","!int"); }
		@Test public void test_71() { testValid("!int","{{any}}"); }
		@Test public void test_72() { testValid("!int","{{int}}"); }
		@Test public void test_73() { testValid("!int","{!int}"); }
		@Test public void test_74() { testInvalid("!int","!{any}"); }
		@Test public void test_75() { testInvalid("!int","!{int}"); }
		@Test public void test_76() { testInvalid("!int","!!any"); }
		@Test public void test_77() { testInvalid("!int","!!int"); }
		@Test public void test_78() { testInvalid("{{any}}","any"); }
		@Test public void test_79() { testInvalid("{{any}}","int"); }
		@Test public void test_80() { testInvalid("{{any}}","{any}"); }
		@Test public void test_81() { testInvalid("{{any}}","{int}"); }
		@Test public void test_82() { testValid("{{any}}","!any"); }
		@Test public void test_83() { testInvalid("{{any}}","!int"); }
		@Test public void test_84() { testValid("{{any}}","{{any}}"); }
		@Test public void test_85() { testValid("{{any}}","{{int}}"); }
		@Test public void test_86() { testInvalid("{{any}}","{!int}"); }
		@Test public void test_87() { testInvalid("{{any}}","!{any}"); }
		@Test public void test_88() { testInvalid("{{any}}","!{int}"); }
		@Test public void test_89() { testInvalid("{{any}}","!!any"); }
		@Test public void test_90() { testInvalid("{{any}}","!!int"); }
		@Test public void test_91() { testInvalid("{{int}}","any"); }
		@Test public void test_92() { testInvalid("{{int}}","int"); }
		@Test public void test_93() { testInvalid("{{int}}","{any}"); }
		@Test public void test_94() { testInvalid("{{int}}","{int}"); }
		@Test public void test_95() { testValid("{{int}}","!any"); }
		@Test public void test_96() { testInvalid("{{int}}","!int"); }
		@Test public void test_97() { testInvalid("{{int}}","{{any}}"); }
		@Test public void test_98() { testValid("{{int}}","{{int}}"); }
		@Test public void test_99() { testInvalid("{{int}}","{!int}"); }
		@Test public void test_100() { testInvalid("{{int}}","!{any}"); }
		@Test public void test_101() { testInvalid("{{int}}","!{int}"); }
		@Test public void test_102() { testInvalid("{{int}}","!!any"); }
		@Test public void test_103() { testInvalid("{{int}}","!!int"); }
		@Test public void test_104() { testInvalid("{!int}","any"); }
		@Test public void test_105() { testInvalid("{!int}","int"); }
		@Test public void test_106() { testInvalid("{!int}","{any}"); }
		@Test public void test_107() { testInvalid("{!int}","{int}"); }
		@Test public void test_108() { testValid("{!int}","!any"); }
		@Test public void test_109() { testInvalid("{!int}","!int"); }
		@Test public void test_110() { testValid("{!int}","{{any}}"); }
		@Test public void test_111() { testValid("{!int}","{{int}}"); }
		@Test public void test_112() { testValid("{!int}","{!int}"); }
		@Test public void test_113() { testInvalid("{!int}","!{any}"); }
		@Test public void test_114() { testInvalid("{!int}","!{int}"); }
		@Test public void test_115() { testInvalid("{!int}","!!any"); }
		@Test public void test_116() { testInvalid("{!int}","!!int"); }
		@Test public void test_117() { testInvalid("!{any}","any"); }
		@Test public void test_118() { testValid("!{any}","int"); }
		@Test public void test_119() { testInvalid("!{any}","{any}"); }
		@Test public void test_120() { testInvalid("!{any}","{int}"); }
		@Test public void test_121() { testValid("!{any}","!any"); }
		@Test public void test_122() { testInvalid("!{any}","!int"); }
		@Test public void test_123() { testInvalid("!{any}","{{any}}"); }
		@Test public void test_124() { testInvalid("!{any}","{{int}}"); }
		@Test public void test_125() { testInvalid("!{any}","{!int}"); }
		@Test public void test_126() { testValid("!{any}","!{any}"); }
		@Test public void test_127() { testInvalid("!{any}","!{int}"); }
		@Test public void test_128() { testInvalid("!{any}","!!any"); }
		@Test public void test_129() { testValid("!{any}","!!int"); }
		@Test public void test_130() { testInvalid("!{int}","any"); }
		@Test public void test_131() { testValid("!{int}","int"); }
		@Test public void test_132() { testInvalid("!{int}","{any}"); }
		@Test public void test_133() { testInvalid("!{int}","{int}"); }
		@Test public void test_134() { testValid("!{int}","!any"); }
		@Test public void test_135() { testInvalid("!{int}","!int"); }
		@Test public void test_136() { testValid("!{int}","{{any}}"); }
		@Test public void test_137() { testValid("!{int}","{{int}}"); }
		@Test public void test_138() { testValid("!{int}","{!int}"); }
		@Test public void test_139() { testValid("!{int}","!{any}"); }
		@Test public void test_140() { testValid("!{int}","!{int}"); }
		@Test public void test_141() { testInvalid("!{int}","!!any"); }
		@Test public void test_142() { testValid("!{int}","!!int"); }
		@Test public void test_143() { testValid("!!any","any"); }
		@Test public void test_144() { testValid("!!any","int"); }
		@Test public void test_145() { testValid("!!any","{any}"); }
		@Test public void test_146() { testValid("!!any","{int}"); }
		@Test public void test_147() { testValid("!!any","!any"); }
		@Test public void test_148() { testValid("!!any","!int"); }
		@Test public void test_149() { testValid("!!any","{{any}}"); }
		@Test public void test_150() { testValid("!!any","{{int}}"); }
		@Test public void test_151() { testValid("!!any","{!int}"); }
		@Test public void test_152() { testValid("!!any","!{any}"); }
		@Test public void test_153() { testValid("!!any","!{int}"); }
		@Test public void test_154() { testValid("!!any","!!any"); }
		@Test public void test_155() { testValid("!!any","!!int"); }
		@Test public void test_156() { testInvalid("!!int","any"); }
		@Test public void test_157() { testValid("!!int","int"); }
		@Test public void test_158() { testInvalid("!!int","{any}"); }
		@Test public void test_159() { testInvalid("!!int","{int}"); }
		@Test public void test_160() { testValid("!!int","!any"); }
		@Test public void test_161() { testInvalid("!!int","!int"); }
		@Test public void test_162() { testInvalid("!!int","{{any}}"); }
		@Test public void test_163() { testInvalid("!!int","{{int}}"); }
		@Test public void test_164() { testInvalid("!!int","{!int}"); }
		@Test public void test_165() { testInvalid("!!int","!{any}"); }
		@Test public void test_166() { testInvalid("!!int","!{int}"); }
		@Test public void test_167() { testInvalid("!!int","!!any"); }
		@Test public void test_168() { testValid("!!int","!!int"); }
	}
}
